name: Daily Newsletter Mailer

on:
  schedule:
    # 매일 오전 7시 (UTC 22:00 = KST 07:00)
    - cron: '0 22 * * *'
  workflow_dispatch: # 수동 실행 가능

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: joungsik/gopher-post

jobs:
  send-newsletter:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Gopher Post Newsletter
      run: |
        docker run --rm \
          -e SMTP_HOST="${{ secrets.SMTP_HOST }}" \
          -e SMTP_PORT="${{ secrets.SMTP_PORT }}" \
          -e SMTP_USERNAME="${{ secrets.SMTP_USERNAME }}" \
          -e SMTP_PASSWORD="${{ secrets.SMTP_PASSWORD }}" \
          -e FROM_EMAIL="${{ secrets.FROM_EMAIL }}" \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Notify on failure
      if: failure()
      run: |
        echo "Newsletter sending failed. Check the logs for details."
        # 필요시 Slack, Discord 등으로 알림 전송 가능